/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container": "#171f33",
        "inverse-on-surface": "#283044",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "outline-variant": "#464554",
        "surface": "#0b1326",
        "primary-fixed-dim": "#c0c1ff",
        "error-container": "#93000a",
        "secondary": "#4cd7f6",
        "primary": "#c0c1ff",
        "surface-container-low": "#131b2e",
        "on-tertiary": "#003824",
        "on-tertiary-container": "#000703",
        "on-error": "#690005",
        "background": "#0b1326",
        "on-background": "#dae2fd",
        "secondary-container": "#03b5d3",
        "on-primary-fixed": "#07006c",
        "on-secondary-container": "#00424e",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#001f26",
        "secondary-fixed": "#acedff",
        "inverse-surface": "#dae2fd",
        "tertiary-container": "#00885d",
        "on-surface-variant": "#c7c4d7",
        "tertiary-fixed": "#6ffbbe",
        "tertiary": "#4edea3",
        "surface-tint": "#c0c1ff",
        "outline": "#908fa0",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary": "#003640",
        "inverse-primary": "#494bd6",
        "primary-fixed": "#e1e0ff",
        "on-primary-container": "#0d0096",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-lowest": "#060e20",
        "surface-dim": "#0b1326",
        "on-primary": "#1000a9",
        "on-secondary-fixed-variant": "#004e5c",
        "primary-container": "#8083ff",
        "error": "#ffb4ab",
        "surface-container-high": "#222a3d",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-highest": "#2d3449",
        "on-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "surface-bright": "#31394d"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "1rem",
        "space-xl": "1.5rem",
        "space-lg": "1rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "margin": "1.5rem",
        "space-xs": "0.25rem"
      },
      "fontFamily": {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-code-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "label-code-lg": ["JetBrains Mono", "monospace"],
        "label-code-md": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "body-md": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-code-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "headline-md": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["15px", { "lineHeight": "22px", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "headline-xl-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-code-lg": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "label-code-md": ["11px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}
